/**
 * B3 — the storage adapter, and the traversal it must not permit.
 *
 * The key-safety tests are the important half. Keys are generated by the
 * application today, so none of these inputs can occur — which is exactly why
 * they are worth pinning down, because "a user can never supply a key" is a
 * property of today's callers, not of the backend, and the day it stops being
 * true the backend is what stands between an attachment id and the filesystem.
 */

import { mkdtemp, rm, writeFile, mkdir } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { assertSafeKey, attachmentKey } from "../index";
import { LocalFsBackend } from "../local-fs";

let root: string;
let store: LocalFsBackend;

beforeEach(async () => {
  root = await mkdtemp(join(tmpdir(), "eitekh-storage-"));
  store = new LocalFsBackend(root);
});

afterEach(async () => {
  await rm(root, { recursive: true, force: true });
});

describe("assertSafeKey", () => {
  it("accepts the keys the application generates", () => {
    expect(() => assertSafeKey("attachments/ab/cmu77n8l4000mygc1yrcshw5h")).not.toThrow();
    expect(() => assertSafeKey("attachments/00/x")).not.toThrow();
  });

  it("refuses traversal in every form", () => {
    for (const bad of [
      "../etc/passwd",
      "attachments/../../etc/passwd",
      "attachments/ab/../../../secret",
      "..",
      "a/../../b",
    ]) {
      expect(() => assertSafeKey(bad)).toThrow(/Unsafe storage key/);
    }
  });

  it("refuses absolute paths and drive letters", () => {
    for (const bad of ["/etc/passwd", "\\\\server\\share\\x", "C:\\Windows\\system32"]) {
      expect(() => assertSafeKey(bad)).toThrow(/Unsafe storage key/);
    }
  });

  it("refuses null bytes, newlines and empty keys", () => {
    for (const bad of ["", "a\u0000b", "a\nb", " leading-space", "trailing-space "]) {
      expect(() => assertSafeKey(bad)).toThrow(/Unsafe storage key/);
    }
  });

  it("refuses a key long enough to be a payload", () => {
    expect(() => assertSafeKey("a".repeat(500))).toThrow(/Unsafe storage key/);
  });
});

describe("attachmentKey", () => {
  it("shards so no single directory or prefix holds everything", () => {
    const a = attachmentKey("cmu77n8l4000mygc1yrcshw5h");
    const b = attachmentKey("cmu77n8l4000mygc1yrcshw99");
    expect(a).not.toBe(b);
    expect(a.startsWith("attachments/")).toBe(true);
    // The shard is derived from the id, so the same id always lands in the
    // same place — a migration that reruns must not scatter duplicates.
    expect(attachmentKey("cmu77n8l4000mygc1yrcshw5h")).toBe(a);
  });

  it("produces a key the backend will accept", () => {
    expect(() => assertSafeKey(attachmentKey("cmu77n8l4000mygc1yrcshw5h"))).not.toThrow();
  });

  it("does not put the user's filename in the key", () => {
    // Filenames carry spaces, slashes, quotes and other people's encodings.
    // They belong in the database, not in a key.
    const key = attachmentKey("cmu77n8l4000mygc1yrcshw5h");
    expect(key).not.toMatch(/\s/);
  });
});

describe("LocalFsBackend", () => {
  const key = attachmentKey("cmu77n8l4000mygc1yrcshw5h");

  it("round-trips bytes exactly", async () => {
    // Binary, not text: a backend that mangles high bytes would pass a test
    // written with "hello".
    const bytes = Buffer.from([0x00, 0xff, 0x10, 0x80, 0x7f, 0xfe]);
    const put = await store.put(key, bytes, "application/octet-stream");

    expect(put.size).toBe(bytes.byteLength);
    expect(await store.readAll(key)).toEqual(bytes);
  });

  it("reports existence honestly", async () => {
    expect(await store.exists(key)).toBe(false);
    await store.put(key, Buffer.from("x"), "text/plain");
    expect(await store.exists(key)).toBe(true);
  });

  it("streams content with the right size", async () => {
    const bytes = Buffer.alloc(4096, 7);
    await store.put(key, bytes, "application/octet-stream");

    const target = await store.read(key);
    expect(target.kind).toBe("stream");
    if (target.kind !== "stream") throw new Error("expected a stream");
    expect(target.size).toBe(4096);

    // Drain it, so a backend that returns a stream nobody can read fails here.
    const reader = target.body.getReader();
    let total = 0;
    for (;;) {
      const { done, value } = await reader.read();
      if (done) break;
      total += value.byteLength;
    }
    expect(total).toBe(4096);
  });

  it("deleting twice is not an error", async () => {
    // A delete that has to be retried should converge rather than fail the
    // second time.
    await store.put(key, Buffer.from("x"), "text/plain");
    await store.delete(key);
    await expect(store.delete(key)).resolves.toBeUndefined();
    expect(await store.exists(key)).toBe(false);
  });

  it("refuses to read outside its root even if a key slipped through", async () => {
    // Plant a real file next to the root and try to reach it.
    const secret = join(root, "..", "eitekh-storage-secret.txt");
    await writeFile(secret, "should never be readable");
    try {
      await expect(store.readAll("../eitekh-storage-secret.txt")).rejects.toThrow();
      await expect(store.put("../escaped.txt", Buffer.from("x"), "text/plain")).rejects.toThrow();
    } finally {
      await rm(secret, { force: true });
    }
  });

  it("creates intermediate directories for a sharded key", async () => {
    // The shard directory does not exist until the first object lands in it.
    await mkdir(root, { recursive: true });
    await store.put(attachmentKey("zzzzzzzzzzzzzzzzzzzzzzzz"), Buffer.from("x"), "text/plain");
    expect(await store.exists(attachmentKey("zzzzzzzzzzzzzzzzzzzzzzzz"))).toBe(true);
  });

  it("declares that it is NOT shared across instances unless told", async () => {
    // Multi-instance is a proven property of this application. A backend that
    // silently breaks it must be refusable at boot.
    expect(new LocalFsBackend(root).isSharedAcrossInstances).toBe(false);
    expect(new LocalFsBackend(root, { shared: true }).isSharedAcrossInstances).toBe(true);
  });
});
