export interface CanonicalReport {
  id: string;
  name: string;
  shortDesc: string;
  category: 'PROJECT' | 'WORK' | 'SPRINT' | 'DELIVERY' | 'TEAM' | 'QUALITY' | 'RISK' | 'PLANNING' | 'ROADMAP' | 'AUDIT';
  categoryLabel: string;
  businessPurpose: string;
  businessQuestion: string;
  scopeFilter: string;
  distinctMatrix: string;
  targetAudience: string;
  keyMetrics: string[];
  differenceSummary: string;
  iconName: string;
  tags: string[];
}

export const CANONICAL_REPORTS: CanonicalReport[] = [
  {
    id: 'project-overview',
    name: 'Project Executive Overview',
    shortDesc: 'Comprehensive executive snapshot of project health, scope delivery, milestones, and strategic risks.',
    category: 'PROJECT',
    categoryLabel: 'Executive & Portfolio',
    businessPurpose: 'Provide senior management and stakeholders with high-level visibility into overall project trajectory, milestone adherence, and key delivery risks.',
    businessQuestion: 'Are we on track to deliver our project objectives, and what are the major risks to delivery?',
    scopeFilter: 'Full Project Scope (All Work Items & Initiatives)',
    distinctMatrix: 'Executive Health Scorecard & Strategic Epics Progress',
    targetAudience: 'Project Sponsors, CTO, VP Engineering, Product Directors',
    keyMetrics: ['Overall Completion %', 'Story Points Burned', 'Active Work In Progress', 'At-Risk Deliverables'],
    differenceSummary: 'The macro executive scorecard. Unlike micro operational reports, it aggregates all project vectors into an overall health assessment for leadership.',
    iconName: 'Briefcase',
    tags: ['Executive', 'Health', 'Milestones', 'Scope'],
  },
  {
    id: 'work-portfolio',
    name: 'Work Portfolio Analysis',
    shortDesc: 'Consolidated breakdown of work items across statuses, priorities, issue types, epics, and teams.',
    category: 'WORK',
    categoryLabel: 'Work Portfolio',
    businessPurpose: 'Understand portfolio composition, identify priority imbalances, and monitor work distribution across all dimensions.',
    businessQuestion: 'What does our total backlog and active work look like by type, priority, and workflow stage?',
    scopeFilter: 'All Active Project Deliverables across all issue types',
    distinctMatrix: 'Status Distribution Matrix, Priority Severity Breakdown, Issue Type Scope Matrix, Strategic Epics Matrix',
    targetAudience: 'Product Managers, Engineering Directors, Portfolio Planners',
    keyMetrics: ['Total Scope Items', 'WIP Pipeline', 'Delivered Scope', 'Unassigned Scope'],
    differenceSummary: 'Structural composition analysis. Shows the shape and balance of the entire workload (e.g. ratio of features vs technical debt vs bugs) rather than sprint time-boxes.',
    iconName: 'Layers',
    tags: ['Portfolio', 'Status', 'Priority', 'Type Distribution'],
  },
  {
    id: 'sprint-performance',
    name: 'Sprint Performance',
    shortDesc: 'Iteration velocity, committed vs delivered points, burndown trajectory, scope creep, and carryover analysis.',
    category: 'SPRINT',
    categoryLabel: 'Sprint & Iterations',
    businessPurpose: 'Measure sprint predictability, velocity trends, team commitment reliability, and iteration burndown progress.',
    businessQuestion: 'Did the team deliver what was committed for this sprint, and what was our actual burned velocity?',
    scopeFilter: 'Strictly Scoped to Active / Selected Sprint Items',
    distinctMatrix: 'Sprint Burndown Trajectory, Velocity Scorecard, Committed vs Delivered Points',
    targetAudience: 'Scrum Masters, Agile Coaches, Engineering Leads, Delivery Teams',
    keyMetrics: ['Committed Sprint Scope', 'Delivered Points', 'Remaining In-Flight', 'Sprint Delivery Pace %'],
    differenceSummary: 'Iteration time-box report. Strictly isolates items assigned to the active sprint to measure velocity predictability and burndown rate.',
    iconName: 'Flame',
    tags: ['Velocity', 'Burndown', 'Burnup', 'Carryover'],
  },
  {
    id: 'delivery-flow',
    name: 'Delivery & Flow Analysis',
    shortDesc: 'End-to-end throughput, average cycle time, backlog lead time, work-in-progress (WIP), and process bottlenecks.',
    category: 'DELIVERY',
    categoryLabel: 'Delivery & Flow',
    businessPurpose: 'Identify workflow bottlenecks, track delivery velocity from intake to deployment, and optimize work-in-progress limits.',
    businessQuestion: 'How fast do items move from inception to completion, and where are tasks queuing or stalling?',
    scopeFilter: 'Completed and In-Progress Deliverables with Lifecycle Timestamps',
    distinctMatrix: 'Cycle Duration Distribution, WIP Queue Depth, Throughput vs Intake Pace',
    targetAudience: 'DevOps Leads, Agile Delivery Managers, Process Improvement Leads',
    keyMetrics: ['Avg Cycle Duration (days)', 'Throughput Delivered', 'Active Work In Progress', 'Intake vs Delivery Ratio'],
    differenceSummary: 'Process velocity and lead-time report. Focuses on speed of movement through workflow stages rather than static counts or assignments.',
    iconName: 'TrendingUp',
    tags: ['Cycle Time', 'Lead Time', 'Throughput', 'WIP'],
  },
  {
    id: 'team-capacity',
    name: 'Team Performance & Capacity',
    shortDesc: 'Capacity utilization, individual workload distribution, team throughput, and unassigned work allocation.',
    category: 'TEAM',
    categoryLabel: 'Team & Capacity',
    businessPurpose: 'Balance contributor workloads, detect over-allocated or under-utilized members, and optimize sprint capacity planning.',
    businessQuestion: 'Who has too much on their plate, who has capacity, and what work remains unassigned?',
    scopeFilter: 'All Project Items mapped to Assignees and Contributor profiles',
    distinctMatrix: 'Team Capacity & Workload Matrix (Standard Capacity, Utilization %, Workload Status)',
    targetAudience: 'Engineering Managers, Team Leads, Resource Managers',
    keyMetrics: ['Active Contributors', 'Assigned Workload (pts)', 'Avg Contributor Load', 'Unassigned Scope'],
    differenceSummary: 'Resource allocation report. Evaluates individual team member utilization percentages and highlights overloaded vs available contributors.',
    iconName: 'Users',
    tags: ['Capacity', 'Utilization', 'Workload', 'Contributors'],
  },
  {
    id: 'quality-defect',
    name: 'Quality & Defect Analysis',
    shortDesc: 'Defect intake vs resolution rate, severity distribution, reopen rates, and software stability metrics.',
    category: 'QUALITY',
    categoryLabel: 'Quality & Defects',
    businessPurpose: 'Monitor product quality, track critical bug remediation time, and identify components generating excessive rework.',
    businessQuestion: 'How stable is the product, how many critical bugs are open, and are we resolving defects faster than they are found?',
    scopeFilter: 'Strictly Filtered to Bug & Defect Issue Types',
    distinctMatrix: 'Defect Severity Triage Register, Defect Fix & Verification Ratio',
    targetAudience: 'QA Leads, Test Automation Engineers, Engineering Leads, Product Quality Managers',
    keyMetrics: ['Total Defects Reported', 'Critical / High Defects', 'Resolved & Verified', 'Defect Resolution Rate %'],
    differenceSummary: 'Quality and defect register. Filters out normal user stories and tasks to focus exclusively on software defects, severities, and bug triage.',
    iconName: 'Bug',
    tags: ['Bugs', 'Defect Rate', 'Severity', 'Stability'],
  },
  {
    id: 'risk-exception',
    name: 'Risk & Exception Report',
    shortDesc: 'Actionable register of overdue deliverables, blocked dependencies, critical SLA breaches, and delivery risks.',
    category: 'RISK',
    categoryLabel: 'Risk & Exceptions',
    businessPurpose: 'Spotlight items needing immediate management intervention to prevent schedule slippage and deliverable failure.',
    businessQuestion: 'What items are overdue, blocked by dependencies, or breaching critical delivery thresholds right now?',
    scopeFilter: 'Strictly Filtered to Overdue, Blocked, and Critical SLA Breach Items',
    distinctMatrix: 'SLA Breach Register (+Xd Overdue), Dependency Blocker Matrix',
    targetAudience: 'Project Managers, Delivery Leads, Risk & Compliance Officers',
    keyMetrics: ['Overdue Deliverables', 'Blocked Work Items', 'Critical Open Issues', 'Points at Immediate Risk'],
    differenceSummary: 'Exception-only action register. Strips away green/healthy items to present an actionable punch list of items requiring urgent intervention.',
    iconName: 'AlertTriangle',
    tags: ['Overdue', 'Blocked', 'SLA Breach', 'Exceptions'],
  },
  {
    id: 'backlog-planning',
    name: 'Backlog & Planning Analysis',
    shortDesc: 'Backlog grooming readiness, estimation coverage, unassigned items, aging, and sprint readiness.',
    category: 'PLANNING',
    categoryLabel: 'Backlog & Planning',
    businessPurpose: 'Evaluate sprint refinement readiness, ensure work items are properly estimated and scoped before iteration planning.',
    businessQuestion: 'Is our backlog refined, sized with story points, and ready for upcoming iteration commitments?',
    scopeFilter: 'Unscheduled Backlog Items (Items not yet assigned to an active sprint)',
    distinctMatrix: 'Story Point Estimation Coverage Matrix, Sprint Refinement Readiness',
    targetAudience: 'Product Owners, Agile Team Leads, Scrum Masters',
    keyMetrics: ['Backlog Scope Items', 'Estimation Coverage %', 'Unassigned Backlog Items', 'Sprint Ready Items'],
    differenceSummary: 'Refinement readiness report. Isolates unscheduled backlog items to assess whether tasks have story points, clear descriptions, and readiness for sprint intake.',
    iconName: 'Target',
    tags: ['Backlog', 'Refinement', 'Estimation', 'Readiness'],
  },
  {
    id: 'roadmap-milestones',
    name: 'Roadmap & Milestone Status',
    shortDesc: 'Strategic epics burnup, release milestone progress, schedule deadlines, and initiative roadmaps.',
    category: 'ROADMAP',
    categoryLabel: 'Roadmaps & Epics',
    businessPurpose: 'Track progress against long-term strategic initiatives and forecasted delivery dates for major business milestones.',
    businessQuestion: 'How far along are our strategic epics and when will key business initiatives reach completion?',
    scopeFilter: 'Parent Epics, Strategic Initiatives, and their Child Deliverables',
    distinctMatrix: 'Epic Initiatives Burnup Table, Target Date Milestone Tracker',
    targetAudience: 'Product Executives, Portfolio Managers, Business Stakeholders',
    keyMetrics: ['Active Strategic Epics', 'Linked Work Items', 'Initiative Burnup Pace %', 'Completed Deliverables'],
    differenceSummary: 'Strategic time-horizon report. Groups all deliverables by parent Epic to measure long-term milestone completion rather than individual tasks.',
    iconName: 'Compass',
    tags: ['Roadmap', 'Epics', 'Milestones', 'Deadlines'],
  },
  {
    id: 'project-activity',
    name: 'Project Activity & Audit',
    shortDesc: 'Complete traceability audit trail of status changes, reassignments, priority updates, and system events.',
    category: 'AUDIT',
    categoryLabel: 'Audit & Governance',
    businessPurpose: 'Provide end-to-end governance and compliance traceability for all changes performed across project records.',
    businessQuestion: 'Who changed what, when was this status or priority modified, and is there a verifiable audit trail?',
    scopeFilter: 'All Project Change Events, State Transitions, and Audit Records',
    distinctMatrix: 'System Activity Ledger, Immutable Event Audit Stream',
    targetAudience: 'Compliance Officers, Auditors, Enterprise Administrators, Team Leads',
    keyMetrics: ['Tracked System Events', 'Audited Work Items', 'Modified Deliverables', 'Ledger Integrity 100%'],
    differenceSummary: 'Governance and change ledger. Rather than measuring metrics, it provides an immutable timeline of who changed what, when, and why.',
    iconName: 'History',
    tags: ['Audit Log', 'Traceability', 'Governance', 'History'],
  },
];

export const CANONICAL_REPORT_CATEGORIES = [
  { id: 'ALL', label: 'All 10 Reports' },
  { id: 'PROJECT', label: 'Executive & Portfolio' },
  { id: 'SPRINT', label: 'Sprint & Delivery' },
  { id: 'TEAM', label: 'Team & Quality' },
  { id: 'RISK', label: 'Risk & Planning' },
  { id: 'AUDIT', label: 'Audit & Governance' },
];
