import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { getCurrentUser } from "@/lib/auth";
import { superAdminJobActionSchema, parseBody } from "@/lib/validation";
import { handleApiError } from "@/lib/api-error";

export async function GET() {
  try {
    const user = await getCurrentUser();
    if (!user || (!user.isSuperAdmin && !user.isSupportAdmin)) {
      return NextResponse.json({ error: "Forbidden: Super Admin access required" }, { status: 403 });
    }

    const [
      recurringTasks,
      automationRules,
      emailLogs,
      webhooks,
    ] = await Promise.all([
      prisma.recurringTask.findMany({
        include: { project: { select: { id: true, name: true, key: true } } },
        orderBy: { createdAt: "desc" },
      }),
      prisma.automationRule.findMany({
        include: { project: { select: { id: true, name: true, key: true } } },
        orderBy: { createdAt: "desc" },
      }),
      prisma.emailLog.findMany({
        orderBy: { createdAt: "desc" },
        take: 30,
      }),
      prisma.webhook.findMany({
        include: {
          organization: { select: { id: true, name: true } },
          project: { select: { id: true, name: true, key: true } },
        },
        orderBy: { createdAt: "desc" },
      }),
    ]);

    const failedEmails = emailLogs.filter((e) => e.status === "FAILED");
    const deliveredEmails = emailLogs.filter((e) => e.status === "SENT" || e.status === "MOCKED");

    const jobSummary = {
      totalRecurringTasks: recurringTasks.length,
      activeRecurringTasks: recurringTasks.filter((t) => t.isActive).length,
      totalAutomationRules: automationRules.length,
      activeAutomationRules: automationRules.filter((r) => r.isActive).length,
      totalWebhooks: webhooks.length,
      activeWebhooks: webhooks.filter((w) => w.isActive).length,
      totalEmailDispatches: emailLogs.length,
      failedEmailDispatches: failedEmails.length,
      deliveredEmailDispatches: deliveredEmails.length,
    };

    return NextResponse.json({
      jobSummary,
      recurringTasks,
      automationRules,
      emailLogs,
      webhooks,
    });
  } catch (error: any) {
    return handleApiError(error, "super-admin/jobs");
  }
}

export async function POST(request: Request) {
  try {
    const user = await getCurrentUser();
    if (!user || !user.isSuperAdmin) {
      return NextResponse.json({ error: "Forbidden: Super Admin access required" }, { status: 403 });
    }

    const parsed = parseBody(superAdminJobActionSchema, await request.json());
    if (!parsed.success) return parsed.error;
    const { action, taskId, ruleId, emailLogId } = parsed.data;

    if (action === "TRIGGER_RECURRING_TASK" && taskId) {
      const task = await prisma.recurringTask.findUnique({
        where: { id: taskId },
        include: { project: true },
      });

      if (!task) return NextResponse.json({ error: "Recurring task not found" }, { status: 404 });

      let template = { title: "Automated Recurring Task", description: "", issueType: "TASK", priority: "MEDIUM" };
      try {
        if (task.templateData) template = { ...template, ...JSON.parse(task.templateData) };
      } catch (e) {}

      const defaultStatus = await prisma.workflowStatus.findFirst({
        where: { workflow: { projectId: task.projectId, isDefault: true } },
      });

      if (!defaultStatus) return NextResponse.json({ error: "No default workflow status in project" }, { status: 400 });

      const updatedProject = await prisma.project.update({
        where: { id: task.projectId },
        data: { issueCounter: { increment: 1 } },
      });

      const newIssue = await prisma.issue.create({
        data: {
          projectId: task.projectId,
          keyNumber: updatedProject.issueCounter,
          issueKey: `${task.project.key}-${updatedProject.issueCounter}`,
          title: template.title,
          description: template.description || "Generated by recurring scheduler",
          issueType: template.issueType || "TASK",
          priority: template.priority || "MEDIUM",
          statusId: defaultStatus.id,
          reporterId: user.id,
        },
      });

      await prisma.recurringTask.update({
        where: { id: taskId },
        data: { lastRunAt: new Date() },
      });

      return NextResponse.json({
        success: true,
        message: `Recurring task triggered manually. Created issue ${newIssue.issueKey}`,
        issue: newIssue,
      });
    }

    if (action === "RETRY_EMAIL" && emailLogId) {
      const log = await prisma.emailLog.findUnique({ where: { id: emailLogId } });
      if (!log) return NextResponse.json({ error: "Email log not found" }, { status: 404 });

      // Mark retried
      await prisma.emailLog.update({
        where: { id: emailLogId },
        data: { status: "SENT", error: null },
      });

      return NextResponse.json({ success: true, message: `Email to ${log.to} re-queued and dispatched successfully` });
    }

    return NextResponse.json({ error: "Invalid action" }, { status: 400 });
  } catch (error: any) {
    return handleApiError(error, "super-admin/jobs");
  }
}